### ISSUE TITLE
CD-R1 Sensores de monitoreo

### ISSUE THREAD

**Issue by JuanJDlp** [JuanJDlp/ParkTrack#12]
Como evaluador, quiero monitorear la movilidad del pie y la pierna durante las pruebas de zapateo y taconeo mediante sensores, para obtener datos precisos sobre la movilidad del evaluado.

Criterios de Aceptación:

* Los sensores deben poder calcular cuando el pie o la pierna se muevan al momento de realizar las pruebas.

**Comment by Domiciano** [comment]
Regularmente, después del quiero va un verbo en infitivo ya que estoy describiendo una acción de mi usuario en el sistema. Esta acción es la necesidad de mi usuario
