### ISSUE TITLE
CD-R2 Controlador principal de sensores

### ISSUE THREAD

**Issue by JuanJDlp** [JuanJDlp/ParkTrack#13]
Como evaluador, quiero utilizar un dispositivo para recolectar información del paciente antes de enviarla al servidor, para asegurar que los datos sean correctos.

Criterios de Aceptación:

* El controlador debe almacenar los datos temporalmente hasta que se confirme que la recolección fue exitosa.
* El controlador debe asegurar que los datos captados por los sensores se guarden correctamente antes de proceder con la transmisión.

**Comment by Domiciano** [comment]
Se puede reescribir como:

Como evaluador, quiero utilizar el dispositivo electrónico para recolectar información del paciente antes de enviarla al servidor, para asegurar que los datos sean correctos
