### ISSUE TITLE
CD-R3 Creación de Metadatos de Muestra

### ISSUE THREAD

**Issue by JuanJDlp** [JuanJDlp/ParkTrack#14]
Como evaluador, quiero acceder a los datos en bruto de una prueba, incluyendo el ID del evaluado, el tipo de prueba, la fecha, la hora y la ubicación, para asegurar que la información recolectada sea precisa y esté lista para su análisis posterior.

Criterios de aceptación:

* Los datos en bruto recolectados por los sensores deben incluir los siguientes metadatos:
* ID del evaluado (proporcionado desde AR-R1).
* Tipo de prueba (definido por AR-R6).
* Fecha y hora exacta de la realización de la prueba.
* Ubicación geográfica donde se realizó la prueba.
* El paquete debe estar compuesto por la muestra (datos en bruto) y los metadatos (etiquetado).
* El formato del paquete debe ser compatible con el servidor central para su almacenamiento y procesamiento.
* El sistema debe validar que todos los metadatos estén presentes y correctamente asignados antes de preparar el paquete para su envío.
* El paquete (muestra + etiquetado) debe estar listo para ser enviado inmediatamente después de la recolección y etiquetado de los datos.
* Si algún metadato requerido falta o es incorrecto, el sistema debe generar una alerta y no permitir el envío hasta que el error sea corregido.

**Comment by Domiciano** [comment]
Cambiar por verbo en infinitivo. El quiero debe describir la necesidad del usuario, una acción del usuario en el sistema. No describe una acción del sistema
